### ISSUE TITLE
[Docs RFC] Implement variables across docs

### ISSUE THREAD

**Issue by atovpeko** [timescale/docs#3456]
Implement [variables](https://github.com/timescale/web-documentation/blob/production-v3/vars.js) to docs per section:

```[tasklist]
### Tasks
- [ ] Get started
- [ ] Use
- [ ] Tutorials
- [ ] Code quick start
- [ ] API reference
- [ ] Migrate
- [ ] Other deployment options
- [ ] About
- [ ] AI and Vector
```
