### ISSUE TITLE
Bucket for Install  overhaul issues

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#463]
Use this issue to collect all the issues that need to be addressed when the install and getting started sections are overhauled.

- [x] https://github.com/timescale/docs/issues/235
- [x] https://github.com/timescale/web-documentation/issues/242
- [x] https://github.com/timescale/docs/issues/466
- [x] https://github.com/timescale/docs/issues/513
- [x] https://github.com/timescale/docs-private/issues/12
- [x] https://github.com/timescale/docs/issues/399
